Updated to v1.3
- Migrated to latest MMT-Reborn Template
- Added 32-bit support
- Written code from scratch
- Added three new modes i.e Fast, Faster & Fastest
- Misc. changes & fixes

Signed-off-by: iamlooper <iamloooper@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -4,46 +4,33 @@
 # INIT
 ######
 
-umask 022
+umask 0022
 
 # Global vars
-TMPDIR=/dev/tmp
-PERSISTDIR=/sbin/.magisk/mirror/persist
+TMPDIR="/dev/tmp"
+PERSISTDIR="/sbin/.magisk/mirror/persist"
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $TMPDIR
+# Echo before loading util_functions
+ui_print() { echo "$@"; }
 
-# echo before loading util_functions
-ui_print() { echo "$1"; }
+load_vksel() { source "$MODPATH/addon/Volume-Key-Selector/install.sh"; }
 
-require_new_magisk() {
-  ui_print "*******************************"
-  ui_print " Please install Magisk v19.0+! "
-  ui_print "*******************************"
-  exit 1
-}
+rmtouch() { [[ -e "$1" ]] && rm -rf "$1" 2>/dev/null; }
 
-is_setup_script() {
-  unzip -l "$ZIPFILE" setup.sh | grep -q setup.sh
-  return $?
-}
+rmtouch "$TMPDIR"
+mkdir -p "$TMPDIR"
 
 ####################
 # SETUP ENVIRONMENT
 ####################
 
-OUTFD=$2
-ZIPFILE=$3
+OUTFD="$2"
+ZIPFILE="$3"
 
 mount /data 2>/dev/null
 
 # Load utility functions
-if [ -f /data/adb/magisk/util_functions.sh ]; then
-  . /data/adb/magisk/util_functions.sh
-  NVBASE=/data/adb
-else
-  require_new_magisk
-fi
+source "/data/adb/magisk/util_functions.sh"
 
 # Preperation for flashable zips
 setup_flashable
@@ -55,139 +42,93 @@ mount_partitions
 api_level_arch_detect
 
 # Setup busybox and binaries
-if $BOOTMODE; then
-boot_actions
-else
-recovery_actions
-fi
+"$BOOTMODE" && boot_actions || recovery_actions
 
 ##############
 # PREPARATION
 ##############
 
 # Extract prop file
-unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "[!] Unable to extract zip file!"
+unzip -o "$ZIPFILE" module.prop -d "$TMPDIR" >&2
+[[ ! -f "$TMPDIR/module.prop" ]] && abort "[!] Unable to extract zip file!"
 
+# Mod vars
+NVBASE="/data/adb"
 $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
-MODULEROOT=$NVBASE/$MODDIRNAME
-MODID=$(grep_prop id $TMPDIR/module.prop)
-MODPATH=$MODULEROOT/$MODID
-MODNAME=$(grep_prop name $TMPDIR/module.prop)
+MODULEROOT="$NVBASE/$MODDIRNAME"
+MODID="$(grep_prop "id" "$TMPDIR/module.prop")"
+MODPATH="$MODULEROOT/$MODID"
+MODNAME="$(grep_prop "name" "$TMPDIR/module.prop")"
 
 # Create mod paths
-rm -rf $MODPATH 2>/dev/null
-mkdir -p $MODPATH
+rmtouch "$MODPATH"
+mkdir -p "$MODPATH"
 
 ##############
 # INSTALLATION
 ##############
 
-# Extract modname_print to $MODPATH
-unzip -o "$ZIPFILE" banner service.sh -d $MODPATH >&2
-
-if is_setup_script; then
-unzip -oj "$ZIPFILE" module.prop setup.sh uninstall.sh -d $TMPDIR >&2
+# Extract to $MODPATH
+unzip -o "$ZIPFILE" -d "$MODPATH" >&2
 
 # Load install script
-. $TMPDIR/setup.sh
+source "$MODPATH/setup.sh"
 
 # Remove all old files before doing installation if want to
-  if [ "$CLEANSERVICE" = "true" ]; then
-    rm -rf /data/adb/modules/${MODID}/* 2>/dev/null
-  fi
+"$CLEANSERVICE" && rm -rf "/data/adb/modules/$MODID"
 
 # Enable debugging if true
-  if [ "$DEBUG" = "true" ]; then
-    set -x
-  else
-    set +x
-  fi
+"$DEBUG" && set -x || set +x
 
-# Callback 01
-mod_info_print
+# Print mod info
+info_print
 
-# Unzipping under auto extraction
-if [[ "$AUTOUNZIP" = "true" ]]; then
-   if [ -e "$MODPATH/addon" ] ; then
-   unzip -o "$ZIPFILE" 'addon/*' -d $TMPDIR >&2
+# Auto vskel load
+"$AUTOVKSEL" && load_vksel
 
-   elif [ -e "$MODPATH/system" ]; then
-   unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
-   fi
-fi
-
-# Callback 02
-install_module
-
-# Custom uninstaller
-  if [ -f $TMPDIR/uninstall.sh ]; then 
-    cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
-  fi
+# Main
+init_main
 
 # Skip mount
-  if [ "$SKIPMOUNT" = "true" ]; then
-    touch $MODPATH/skip_mount
-  fi
-
-# Prop file
-  if [ "$PROPFILE" = "false" ]; then
-    rm -rf $MODPATH/system.prop
-  fi
-
-# Post-fs-data script
-  if [ "$POSTFSDATA" = "false" ]; then
-    rm -rf $MODPATH/post-fs-data.sh
-  fi
-
-# Service script
-  if [ "$LATESTARTSERVICE" = "false" ]; then
-    rm -rf $MODPATH/service.sh
-  fi
-
-# Module info
-cp -af $TMPDIR/module.prop $MODPATH/module.prop
+"$SKIPMOUNT" && touch "$MODPATH/skip_mount"
 
 # Set permissions
 set_permissions
 
-else
-ui_print "[*] Module setup script not found, exiting installation..."
-exit 1
-fi
-
 # Handle replace folders
 for TARGET in $REPLACE; do
   ui_print "[*] Replace target: $TARGET"
-  mktouch $MODPATH$TARGET/.replace
+  mktouch "$MODPATH$TARGET/.replace"
 done
 
-if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch $NVBASE/modules/$MODID/update
-  cp -af $MODPATH/module.prop $NVBASE/modules/$MODID/module.prop
-fi
+"$BOOTMODE" && {
+  # Update info for Magisk app
+  mktouch "$NVBASE/modules/$MODID/update"
+  cp -af "$MODPATH/module.prop" "$NVBASE/modules/$MODID/module.prop"
+}
 
 # Copy over custom sepolicy rules
-if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
-  ui_print "[*] Installing custom sepolicy patch"
-  PERSISTMOD=$PERSISTDIR/magisk/$MODID
-  mkdir -p $PERSISTMOD
-  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule
-fi
+[[ -f "$MODPATH/sepolicy.rule" ]] && {
+  ui_print "[*] Installing custom sepolicy rules..."
+  copy_sepolicy_rules
+}
 
 # Remove stuffs that don't belong to modules
-rm -rf $MODPATH/LICENSE
+rmtouch "$MODPATH/META-INF"
+rmtouch "$MODPATH/addon"
+rmtouch "$MODPATH/setup.sh"
+rmtouch "$MODPATH/LICENSE"
+rmtouch "$MODPATH/README.md"
+rmtouch "$MODPATH/changelog.md"
+rmtouch "$MODPATH/xcharge.png"
+rmtouch "$MODPATH/system/bin/xcharge64"
+rmtouch "$MODPATH/system/bin/xcharge32"
 
 ##############
 # Finalizing
 ##############
 
 cd /
-if ! $BOOTMODE; then
-recovery_cleanup
-fi
-rm -rf $TMPDIR
-
-ui_print "[*] Done"
+"$BOOTMODE" || recovery_cleanup
+rmtouch "$TMPDIR"
 exit 0
